<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "    <head>\n";
echo "        <meta charset=\"utf-8\" />\n";
echo "        <title>Curriculum Vitae</title>\n";
echo "            <link rel=\"stylesheet\" href=\"css/reset.css\" />\n";
echo "            <link rel=\"stylesheet\" href=\"css/text.css\" />\n";
echo "            <link rel=\"stylesheet\" href=\"css/960.css\" />  \n";
echo "            <link rel=\"stylesheet\" href=\"css/960_24_col.css\" />\n";
echo "            <link rel=\"stylesheet\" href=\"design.css\"  />\n";
echo "        </head>\n";
echo "    <body>\n";
echo "\n";
echo "    <div class=\"container_24\" style=\"background-color:#669999 ; margin-top: 100px;\">\n";
echo "        <div class=\"grid_11\" style=\"background-color:#CC9999 ; border: 5px solid #132951\">\n";
echo "            <img src=\"manusia.jpg\" height=\"300\" width=\"300\" align=\"center\" alt=\"\" class=\"img\">\n";
echo "            <h3>Nadia Ristya Dewi</h3>\n";
echo "            <h6>Informatics Student</h6>\n";
echo "            <h6>UPN Veteran Jawa Timur</h6>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div class=\"grid_12\" style=\"background-color: #CCCCCC; border: 5px solid #132951;\">\n";
echo "            <h2>Formal Education</h2>\n";
echo "            <pre id=\"t2\">\n";
echo "        2018-Now          UPN Veteran Jawa Timur\n";
echo "        2016-2018           SMAN 2 Padang\n";
echo "        2015-2016           SMAN 5 Samarinda\n";
echo "            2015                SMAN 5 Jambi\n";
echo "        2013-2015           SMPN 7 Jambi\n";
echo "        2012-2013           SMPN 3 Ketapang\n";
echo "        2009-2012          SDN 7 Ketapang\n";
echo "        2006-2009          SDN Pabean 1\n";
echo "        2004-2006          TK Sylva Puspita\n";
echo "            </pre>\n";
echo "\n";
echo "        </div>\n";
echo "\n";
echo "        <div class=\"grid_10\" style=\"background-color:#CCCCCC ;\">\n";
echo "            <h2>Language</h2>\n";
echo "            <pre id=\"t2\">\n";
echo "        Indonesia      &#9899  &#9899  &#9899  &#9899  &#9899\n";
echo "        English           &#9899  &#9899  &#9899  &#9899  &#9898\n";
echo "        Jawa               &#9899  &#9899  &#9899  &#9899  &#9898\n";
echo "        Banjar           &#9899  &#9898  &#9898  &#9898  &#9898\n";
echo "        Melayu           &#9899  &#9899  &#9899  &#9898  &#9898\n";
echo "        Minang          &#9899  &#9899  &#9899  &#9898  &#9898\n";
echo "            </pre>\n";
echo "        </div>\n";
echo "\n";
echo "        <div class=\"grid_14\" style=\"background-color:#CCCCCC ;\">\n";
echo "            <h3>Hobbies</h3>\n";
echo "                <ul>\n";
echo "                    <li><img src=\"travelling.jpg\" width=\"130px\" height=\"130px\"><h2>Travelling</h2></li> \n";
echo "                    <li><img src=\"watching.jpg\" width=\"130px\" height=\"130px\"><h2>Watch Movie</h2></li>\n";
echo "                    <li><img src=\"shopping.jpg\" width=\"130px\" height=\"130px\"><h2>Shopping</h2></li>\n";
echo "                </ul>\n";
echo "        </div>\n";
echo "        <div class=\"grid_24\" style=\"background-color: #132951;\">\n";
echo "            <ul>\n";
echo "                <li><img src=\"youtube.jpg\" width=\"30px\" height=\"30px\"><h2>Nadia Ristya</h2></li> \n";
echo "                <li><img src=\"snapchat.jpg\" width=\"30px\" height=\"30px\"><h2>nadiaristya</h2></li>\n";
echo "                <li><img src=\"instagram.jpg\" width=\"30px\" height=\"30px\"><h2>nadiaristya</h2></li>\n";
echo "                <li><img src=\"email.jpg\" width=\"30px\" height=\"30px\"><h2>nadiaristya@gmail.com</h2></li>\n";
echo "            </ul>\n";
echo "         \n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "        \n";
echo "\n";
echo "    </body>\n";
echo "</html>\n";
?>